from wofost_gym.envs.wofost_base import NPK_Env, Harvest_NPK_Env, Plant_NPK_Env

from wofost_gym.envs.wofost_annual import Limited_NPKW_Env
from wofost_gym.envs.wofost_annual import PP_Env
from wofost_gym.envs.wofost_annual import Limited_NPK_Env
from wofost_gym.envs.wofost_annual import Limited_N_Env
from wofost_gym.envs.wofost_annual import Limited_NW_Env
from wofost_gym.envs.wofost_annual import Limited_W_Env

from wofost_gym.envs.plant_annual import Plant_Limited_NPKW_Env
from wofost_gym.envs.plant_annual import Plant_PP_Env
from wofost_gym.envs.plant_annual import Plant_Limited_NPK_Env
from wofost_gym.envs.plant_annual import Plant_Limited_N_Env
from wofost_gym.envs.plant_annual import Plant_Limited_NW_Env
from wofost_gym.envs.plant_annual import Plant_Limited_W_Env

from wofost_gym.envs.harvest_annual import Harvest_Limited_NPKW_Env
from wofost_gym.envs.harvest_annual import Harvest_PP_Env
from wofost_gym.envs.harvest_annual import Harvest_Limited_NPK_Env
from wofost_gym.envs.harvest_annual import Harvest_Limited_N_Env
from wofost_gym.envs.harvest_annual import Harvest_Limited_NW_Env
from wofost_gym.envs.harvest_annual import Harvest_Limited_W_Env

from wofost_gym.envs.wofost_perennial import Perennial_Limited_NPKW_Env
from wofost_gym.envs.wofost_perennial import Perennial_PP_Env
from wofost_gym.envs.wofost_perennial import Perennial_Limited_NPK_Env
from wofost_gym.envs.wofost_perennial import Perennial_Limited_N_Env
from wofost_gym.envs.wofost_perennial import Perennial_Limited_NW_Env
from wofost_gym.envs.wofost_perennial import Perennial_Limited_W_Env

from wofost_gym.envs.plant_perennial import Perennial_Plant_Limited_NPKW_Env
from wofost_gym.envs.plant_perennial import Perennial_Plant_PP_Env
from wofost_gym.envs.plant_perennial import Perennial_Plant_Limited_NPK_Env
from wofost_gym.envs.plant_perennial import Perennial_Plant_Limited_N_Env
from wofost_gym.envs.plant_perennial import Perennial_Plant_Limited_NW_Env
from wofost_gym.envs.plant_perennial import Perennial_Plant_Limited_W_Env

from wofost_gym.envs.harvest_perennial import Perennial_Harvest_Limited_NPKW_Env
from wofost_gym.envs.harvest_perennial import Perennial_Harvest_PP_Env
from wofost_gym.envs.harvest_perennial import Perennial_Harvest_Limited_NPK_Env
from wofost_gym.envs.harvest_perennial import Perennial_Harvest_Limited_N_Env
from wofost_gym.envs.harvest_perennial import Perennial_Harvest_Limited_NW_Env
from wofost_gym.envs.harvest_perennial import Perennial_Harvest_Limited_W_Env